// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6CpCAp1KVzoJ3j6QyJ0wQQPkgTlA6_Vo',
    appId: '1:919239202094:web:b5a21e63373be7617d96bf',
    messagingSenderId: '919239202094',
    projectId: 'ditonton-63826',
    authDomain: 'ditonton-63826.firebaseapp.com',
    storageBucket: 'ditonton-63826.appspot.com',
    measurementId: 'G-WSE0PWRDX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqkXPySOjhmLhD8F86bvrYc9Y5fi_OUkw',
    appId: '1:919239202094:android:b48b4cc43f9221507d96bf',
    messagingSenderId: '919239202094',
    projectId: 'ditonton-63826',
    storageBucket: 'ditonton-63826.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_FnorFPFcmLWnHmK2reou_mpWbU0LV0',
    appId: '1:919239202094:ios:bd84610d22d779ec7d96bf',
    messagingSenderId: '919239202094',
    projectId: 'ditonton-63826',
    storageBucket: 'ditonton-63826.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
